### ISSUE TITLE
[OpenCL] RuntimeError MEM_COPY_OVERLAP during initialisation of ParticleMonitor

### ISSUE THREAD

**Issue by eltos** [xsuite/xsuite#246]
During initialisation of a Particle monitor using the pyopencl context the following error occours:
```
Traceback (most recent call last):
  File "/xsuite/./monitor_test.py", line 22, in <module>
    monitor = xt.ParticlesMonitor(_context=context,
  File "/xsuite/xtrack/xtrack/monitors.py", line 60, in _monitor_init
    self.xoinitialize(
  File "/xsuite/xobjects/xobjects/hybrid_class.py", line 276, in xoinitialize
    self._reinit_from_xobject(_xobject=self._xobject)
  File "/xsuite/xobjects/xobjects/hybrid_class.py", line 243, in _reinit_from_xobject
    setattr(self, pyname, vv)
  File "/xsuite/xobjects/xobjects/hybrid_class.py", line 48, in __set__
    setattr(container._xobject, self.name, value._xobject)
  File "/xsuite/xobjects/xobjects/struct.py", line 104, in __set__
    self.__get__(instance)._update(value)
  File "/xsuite/xobjects/xobjects/struct.py", line 335, in _update
    self._buffer.update_from_xbuffer(
  File "/xsuite/xobjects/xobjects/context.py", line 341, in update_from_xbuffer
    self.update_from_native(
  File "/xsuite/xobjects/xobjects/context_pyopencl.py", line 417, in update_from_native
    cl.enqueue_copy(
  File "/usr/local/lib/python3.10/dist-packages/pyopencl/__init__.py", line 1903, in enqueue_copy
    return _cl._enqueue_copy_buffer(queue, src, dest, **kwargs)
pyopencl._cl.RuntimeError: clEnqueueCopyBuffer failed: MEM_COPY_OVERLAP
```

Minimum code to reproduce:
```python
#!/usr/bin/env python3

import xobjects as xo
import xtrack as xt

xo.ContextPyopencl.print_devices()
context = xo.ContextPyopencl("0.0")  # For OpenCL GPUs

monitor = xt.ParticlesMonitor(_context=context,
                              start_at_turn=5, stop_at_turn=15,
                              num_particles=100)
```
My setup is an Ubuntu 22.04 with AMD OpenCL drivers (amdgpu-install --usecase=opencl), python 3.10 and the latest xsuite modules (git clone and pip install -e with the fix described in https://github.com/xsuite/xobjects/pull/68 applied and the compiler flag described in xsuite/xsuite#247 set)

**Comment by giadarol** [comment]
Just opened a pull request that should solve this by avoiding the copy:
https://github.com/xsuite/xobjects/pull/79

**Comment by giadarol** [comment]
Should be solved. Don't hesitate to reopen if needed.
