### ISSUE TITLE
[xobjects] TypeError when initializing dynamic size arrays on context Pyopencl

### ISSUE THREAD

**Issue by eltos** [xsuite/xsuite#294]
I initialize a struct containing a dynamic size array on a pyopencl context. I want to explicitly initialize the array with zeros (to prevent random initial values). If at runtime the size of the array happens to be zero, the following exception is thrown:

```python
import numpy as np
import xobjects as xo

class MyStruct(xo.Struct):
    a = xo.Float64[:]

n = 0  # dynamic array size
MyStruct(a=np.zeros(n), _context=xo.ContextPyopencl())
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/xobjects/struct.py", line 358, in __init__
    cls._to_buffer(self._buffer, self._offset, info.value, info)
  File "/usr/local/lib/python3.10/dist-packages/xobjects/struct.py", line 326, in _to_buffer
    field.ftype._to_buffer(buffer, foffset, fvalue, finfo)
  File "/usr/local/lib/python3.10/dist-packages/xobjects/array.py", line 476, in _to_buffer
    buffer.update_from_nplike(coffset, cls._itemtype._dtype, value)
  File "/usr/local/lib/python3.10/dist-packages/xobjects/context_pyopencl.py", line 414, in update_from_nplike
    self.update_from_native(offset, arr.base_data, arr.offset, arr.nbytes)
  File "/usr/local/lib/python3.10/dist-packages/xobjects/context_pyopencl.py", line 356, in update_from_native
    cl.enqueue_copy(
  File "/usr/local/lib/python3.10/dist-packages/pyopencl/__init__.py", line 1935, in enqueue_copy
    return _cl._enqueue_write_buffer(queue, dest, src, **kwargs)
TypeError: _enqueue_write_buffer(): incompatible function arguments. The following argument types are supported:
    1. (queue: pyopencl._cl.CommandQueue, mem: pyopencl._cl.MemoryObjectHolder, hostbuf: object, dst_offset: int = 0, wait_for: object = None, is_blocking: bool = True) -> pyopencl._cl.Event

Invoked with: <pyopencl._cl.CommandQueue object at 0x7fc560d2fc40>, <pyopencl._cl.Buffer object at 0x7fc560d2fd80>, None; kwargs: src_offset=0, dst_offset=24, byte_count=0
```
Note that the exception is caused by the 3rd parameter (`src`) passed to `_enqueue_write_buffer` being `None`

------------

While tracking down the issue, I noticed that the following alternatives works. Is the initialization via numpy array not supported, or is this a bug?

```python
for context in (xo.ContextCpu(), xo.ContextPyopencl()):
    for n in (5,0):
        # unitialized array
        MyStruct(a=n, _context=context)  # no error, but random initial values on pyopencl context
        # initialized array by list
        MyStruct(a=[0]*n, _context=context)  # works
        # initialized array by numpy array
        MyStruct(a=np.zeros(n), _context=context)  # error only for n=0 on Pyopencl context

```

**Comment by giadarol** [comment]
In fact we never meant to support "empty" arrays (size zero). It happens to work on other context just by accident.
Indeed the example works for n=1:

```python
import numpy as np
import xobjects as xo

class MyStruct(xo.Struct):
    a = xo.Float64[:]
 
n = 1  # dynamic array size
MyStruct(a=np.zeros(n), _context=xo.ContextPyopencl( ))
```

We should explicitly check that the given size is larger than zero when an array is instantiaged.

**Comment by eltos** [comment]
I see, then it's clearly not a bug.
I have a use case where it is convenient to allow zero size arrays. Please don't prevent it with an explicit check, I will just use lists (`a=[]`) instead which generalize to n=0 also on pyopencl as mentioned above.

**Comment by giadarol** [comment]
I find it a bit dangerous, this is tested nowhere in the test suite

**Comment by szymonlopaciuk** [comment]
I would say this is a bug in the end. Both `xo.Int8[:](0, _context=xo.ContextPyopencl())` and `xo.Int8[:]([], _context=xo.ContextPyopencl())` work, allocating some 16 bytes of the buffer, but `xo.Int8[:](np.array([]), _context=xo.ContextPyopencl())` breaks. In the case of dynamic arrays, since there is memory, a case can be made that the object 'exists'. If it's needed, I could potentially make it so that the behaviour for normal and numpy arrays between contexts is the same, and throw in a few tests of the C-API?

Btw, for fixed zero-length arrays, there's the same problem. Additionally, in the case analogous to your `MyStruct` above, on OpenCL we get an error trying to allocate a zero-length buffer. That could be disallowed on all contexts, for uniformity?

**Comment by rdemaria** [comment]
I am not too against zero length arrays because it can simply  users' code, which is the spirit of xobjects. It should not cost creation and access  run-time performance for normal arrays though...
