### ISSUE TITLE
Pandas hard dependency not declared

### ISSUE THREAD

**Issue by fsoubelet** [xsuite/xsuite#444]
Hi, 

Installing `xtrack` in a fresh environment (`python -m pip install xtrack`) does not install `pandas` as it is not declared as a dependency.

However, starting an interpreter and trying `import xtrack` leads to the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/me/.mambaforge/envs/test/lib/python3.11/site-packages/xtrack/__init__.py", line 28, in <module>
    from .multiline import Multiline, MultiTwiss
  File "/Users/me/.mambaforge/envs/test/lib/python3.11/site-packages/xtrack/multiline/__init__.py", line 1, in <module>
    from .multiline import Multiline, MultiTwiss
  File "/Users/me/.mambaforge/envs/test/lib/python3.11/site-packages/xtrack/multiline/multiline.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

Quick fix would be to inclue `pandas` as a dependency or simply move the import closer to the location where it would be needed.

**Comment by giadarol** [comment]
I think we rely on pandas in quite a few places.
I would make it a hard dependency at this point

**Comment by giadarol** [comment]
@fsoubelet would you mind opening a small PR for that?

**Comment by fsoubelet** [comment]
Sure
