### ISSUE TITLE
Kernel Compilation Issue with New Xtrack

### ISSUE THREAD

**Issue by fsoubelet** [xsuite/xsuite#476]
Hi, 

I upgraded to the latest `xtrack` (0.54.1) and the kernels compilation crashes. This can be observed simply running `xsuite-prebuild`.

Bellow the error stack from the command:
```
Xcoll not installed, skipping collimator elements
Traceback (most recent call last):
  File "/Users/felixsoubelet/.miniforge/envs/dev/bin/xsuite-prebuild", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/xsuite/cli.py", line 21, in main
    regenerate_kernels()
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/xtrack/prebuild_kernels.py", line 316, in regenerate_kernels
    tracker._build_kernel(
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/xtrack/tracker.py", line 624, in _build_kernel
    if self._context.allow_prebuilt_kernels:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ContextCpu' object has no attribute 'allow_prebuilt_kernels'
```

**Comment by giadarol** [comment]
Do you have the latest xobjects?

**Comment by fsoubelet** [comment]
Indeed I had not seen the new `xobjects` release.

I have updated it but am still getting a different error when running `xsuite-prebuild`. Below the full stack trace:
```
Compiling ContextCpu kernels...
default_only_xtrack_no_config.c:14605:8: error: redefinition of 'rng_get'
double rng_get (uint32_t *s1, uint32_t *s2, uint32_t *s3, uint32_t *s4 ){
       ^
default_only_xtrack_no_config.c:1769:8: note: previous definition is here
double rng_get (uint32_t *s1, uint32_t *s2, uint32_t *s3, uint32_t *s4 ){
       ^
default_only_xtrack_no_config.c:14616:6: error: redefinition of 'rng_set'
void rng_set (uint32_t *s1, uint32_t *s2, uint32_t *s3, uint32_t *s4, uint32_t s ){
     ^
default_only_xtrack_no_config.c:1780:6: note: previous definition is here
void rng_set (uint32_t *s1, uint32_t *s2, uint32_t *s3, uint32_t *s4, uint32_t s ){
     ^
2 errors generated.
Traceback (most recent call last):
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 185, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/Users/felixsoubelet/.miniforge/envs/dev/bin/arm64-apple-darwin20.0.0-clang' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/cffi/ffiplatform.py", line 48, in _build
    dist.run_command('build_ext')
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
    _build_ext.build_extension(self, ext)
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 600, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 187, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/Users/felixsoubelet/.miniforge/envs/dev/bin/arm64-apple-darwin20.0.0-clang' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/felixsoubelet/.miniforge/envs/dev/bin/xsuite-prebuild", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/xsuite/cli.py", line 21, in main
    regenerate_kernels()
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/xtrack/prebuild_kernels.py", line 316, in regenerate_kernels
    tracker._build_kernel(
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/xtrack/tracker.py", line 633, in _build_kernel
    out_kernels = context.build_kernels(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/xobjects/context_cpu.py", line 311, in build_kernels
    so_file = self.compile_kernel(
              ^^^^^^^^^^^^^^^^^^^^
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/xobjects/context_cpu.py", line 437, in compile_kernel
    output_file = ffi_interface.compile(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/cffi/api.py", line 725, in compile
    return recompile(self, module_name, source, tmpdir=tmpdir,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/cffi/recompiler.py", line 1564, in recompile
    outputfilename = ffiplatform.compile('.', ext,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/felixsoubelet/.miniforge/envs/dev/lib/python3.11/site-packages/cffi/ffiplatform.py", line 54, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command '/Users/felixsoubelet/.miniforge/envs/dev/bin/arm64-apple-darwin20.0.0-clang' failed with exit code 1
```

**Comment by giadarol** [comment]
Old xpart? :P
